# Generated by Django 6.0 on 2025-12-12 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barber',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
        migrations.AlterField(
            model_name='barber',
            name='position',
            field=models.CharField(choices=[('J', 'Junior Barber'), ('S', 'Senior Barber'), ('M', 'Master Barber')], max_length=100),
        ),
    ]
