# Generated by Django 6.0 on 2025-12-17 16:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbers', '0002_alter_barber_gender_alter_barber_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='barber',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='barber_photos/'),
        ),
        migrations.AlterField(
            model_name='barber',
            name='experience',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(60)]),
        ),
        migrations.AlterField(
            model_name='barber',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
