# Generated by Django 6.0 on 2026-01-12 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbers', '0003_barber_photo_alter_barber_experience_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('appointment_date', models.DateTimeField()),
                ('contact_phone', models.CharField(max_length=20)),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='barbers.barber')),
            ],
        ),
    ]
